### PR TITLE
Adds collab book for Image similarity

### PR DESCRIPTION
**Pull request by radoondas**
This collab book shows how to:
- upload model into ES from hugging face
- ingest documents that already have 'image embeddings' pre-generated OR
- let you define a small number of random images from the dataset and also generate image embeddings using the CLIP model
- executes a simple query over the set of indexed documents
- optional - creates a simple streamlit UI to show the response (because of images) :)

### CODE REVIEW

**Comment by serenachou** [comment]
@miguelgrinberg @yansavitski @joemcelroy  can we push this one along please :)

**Comment by miguelgrinberg** [comment]
@serenachou I think this notebook is misplaced. It is currently in the `notebooks/search` folder, where we have the more general-purpose tutorial-like notebooks. Wouldn't this belong as a blog supporting notebook?

**Comment by serenachou** [comment]
@miguelgrinberg  you're right it should be in the blog supporting content! can we merge and then move it?

**Comment by serenachou** [comment]
Hmm I was going to merge it, and then pull it into my branch to move. @joemcelroy  @miguelgrinberg  you want to click approve on review and I can move it?

**Comment by miguelgrinberg** [comment]
@serenachou I'm in the process of reviewing and migrating this notebook. I opened a separate PR with the updated version: https://github.com/elastic/elasticsearch-labs/pull/206. I had to make a few changes to get everything to work.

**Comment by miguelgrinberg** [comment]
@serenachou we merged the new version of this notebook #206, so I'm closing this. The public notebook is here: https://github.com/elastic/elasticsearch-labs/blob/main/notebooks/images/image-similarity.ipynb

**Pull request closed without merging**
